### ISSUE TITLE
From UAVs to Quadrupeds: Efficient Numerical Optimal Robot Control Across Different Domains and Platforms

### ISSUE THREAD

**Issue by DanielePucci** [loc2/ws_locomotion-manipulation#8]

**Comment by markusgft** [comment]
Attached the slides of our talk this morning. 
[giftthaler_neunert_slides.pdf](https://github.com/loc2/ws_locomotion-manipulation/files/1475095/giftthaler_efficient_numerical_optimal_control_across_different_regimes.pdf)

 * If you are interested in getting preprints of our upcoming publications, don't hesitate to send an e-mail to mgiftthaler(at)ethz(ch), 

 * Our open-source C++ library for numerical optimal control, motion planning, NMPC, and automatic differentiation of cost functions, constraints (and much more) is online at https://adrlab.bitbucket.io/ct/v2.0/ct_doc/doc/html/index.html
